#138 - Extend integration tests in ci
medizininformatik-initiative/feasibility-backend pull request #144
Opened 2023-06-21 09:21 UTC by michael-82

- add and set up blaze and keycloak
- execute a real query against blaze and check if a result > 0 is returned

2023-07-05 09:37 UTC, EmteZogaf requested changes
For testing that a query is sent and the result is received a single test patient with the same gender as used in the test query should be sufficient. No need to add that many test data.

2023-07-05 10:14 UTC, juliangruendner commented
> For testing that a query is sent and the result is received a single test patient with the same gender as used in the test query should be sufficient. No need to add that many test data.

i agree

2023-07-05 10:18 UTC, juliangruendner requested changes
less testdate should be sufficient - see comment from @EmteZogaf

2023-07-05 12:29 UTC, michael-82 commented on .github/scripts/create-keycloak-user.sh
> +docker exec -u0 integration-test_auth_1 /opt/keycloak/bin/kcadm.sh add-roles --uusername testuser --rolename FeasibilityUser -r feasibility
That is indeed the correct way. See https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.3/html/server_administration_guide/the_admin_cli#user_operations "Creating a user" and "Adding realm roles to a user"

2023-07-05 14:01 UTC, michael-82 commented
Changed according to request(s)

2023-07-19 15:10 UTC, EmteZogaf approved these changes
lgtm

2023-07-20 06:37 UTC, merged